"use client";

import { useEffect, useState } from "react";

const KEY = "link26_disclaimer_v1";

// First-run fiction-simulator disclaimer + the WE-DEPICT / WE-NEVER-DEPICT line
// + third-party-AI disclosure. Shown once (localStorage). Required for the
// responsible-design posture and for App Store review.
export default function Disclaimer() {
  const [open, setOpen] = useState(false);

  useEffect(() => {
    if (typeof window !== "undefined" && !localStorage.getItem(KEY)) setOpen(true);
  }, []);

  if (!open) return null;

  const accept = () => {
    try {
      localStorage.setItem(KEY, "1");
    } catch {
      /* ignore */
    }
    setOpen(false);
  };

  return (
    <div className="fixed inset-0 z-[60] flex items-center justify-center bg-black/90 p-4 font-mono">
      <div className="max-h-[88vh] w-full max-w-xl overflow-y-auto rounded-lg border border-cyan-500/25 bg-[#05080c] p-6 shadow-2xl">
        <h2 className="text-lg font-semibold tracking-wide text-cyan-300">An arcade simulator</h2>
        <p className="mt-2 text-[0.74rem] leading-relaxed text-zinc-300">
          This is a work of fiction — a game inspired by Uplink. It dramatizes the mindset and
          vocabulary of red teaming, OSINT, RF collection and cyber operations to build tension,
          not to teach attacks. Every org, person, network and signal here is invented.
        </p>

        <div className="mt-4 grid grid-cols-2 gap-3 text-[0.66rem]">
          <div className="rounded border border-cyan-800/40 bg-cyan-900/10 p-3">
            <div className="mb-1 font-semibold text-cyan-300">WE DEPICT</div>
            <ul className="list-disc space-y-0.5 pl-4 text-zinc-400">
              <li>real workflow shapes &amp; phase names</li>
              <li>what tools are for, abstractly</li>
              <li>tradeoffs as game stats</li>
              <li>the ethics &amp; rules of engagement</li>
            </ul>
          </div>
          <div className="rounded border border-amber-800/40 bg-amber-900/10 p-3">
            <div className="mb-1 font-semibold text-amber-300">WE NEVER DEPICT</div>
            <ul className="list-disc space-y-0.5 pl-4 text-zinc-400">
              <li>working commands or exploits</li>
              <li>anything that transfers to a real system</li>
              <li>real targets, data or credentials</li>
              <li>person tracking / surveillance</li>
            </ul>
          </div>
        </div>

        <p className="mt-4 text-[0.64rem] leading-relaxed text-zinc-500">
          Some flavor text may be generated by a third-party AI model. Nothing in this game is
          guidance for real-world activity; unauthorized access to systems you don&apos;t own is illegal.
          Play responsibly.
        </p>

        <button
          onClick={accept}
          className="mt-5 w-full rounded border border-cyan-600/50 bg-cyan-800/20 py-2 text-sm font-semibold tracking-wide text-cyan-200 transition-colors hover:bg-cyan-700/30"
        >
          UNDERSTOOD — JACK IN
        </button>
      </div>
    </div>
  );
}
